Repository Nexters/momo-android, pull requests merged in 2023-02, with the labels that each got.

#3 feat #2: Navigation 구현
  .gitignore
  app/build.gradle
  app/src/main/java/com/ovn/momo/app/MainActivity.kt
  app/src/main/java/com/ovn/momo/app/MomoMain.kt
  app/src/main/java/com/ovn/momo/app/MomoNavHost.kt
  app/src/main/java/com/ovn/momo/app/MomoNavigation.kt
  app/src/main/java/com/ovn/momo/core/navigation/MomoComposeNavigator.kt
  app/src/main/java/com/ovn/momo/core/navigation/MomoScreens.kt
  app/src/main/java/com/ovn/momo/core/navigation/NavigationCommand.kt
  app/src/main/java/com/ovn/momo/core/navigation/NavigationModule.kt
  app/src/main/java/com/ovn/momo/core/navigation/Navigator.kt
  app/src/main/java/com/ovn/momo/feature/login/MomoLogin.kt
  app/src/main/java/com/ovn/momo/feature/login/MomoLoginViewModel.kt
  app/src/main/java/com/ovn/momo/feature/signup/SignUpScreen.kt
  app/src/main/java/com/ovn/momo/feature/signup/SignUpViewModel.kt
Labels: feature

#10 feat #9 : 공통 색상/타이포그래피 구현
  app/src/main/java/com/ovn/momo/feature/theme/Color.kt
  app/src/main/java/com/ovn/momo/feature/theme/Shape.kt
  app/src/main/java/com/ovn/momo/feature/theme/Theme.kt
  app/src/main/java/com/ovn/momo/feature/theme/Type.kt
Labels: design

#11 feat #7: 유저 회원가입 탭 구현
  app/build.gradle
  app/src/main/java/com/ovn/momo/app/MomoNavHost.kt
  app/src/main/java/com/ovn/momo/app/MomoNavigation.kt
  app/src/main/java/com/ovn/momo/core/common_ui/CustomOutlinedTextField.kt
  app/src/main/java/com/ovn/momo/core/common_ui/MainRoundBorderButton.kt
  app/src/main/java/com/ovn/momo/feature/signup/SignUpErrorMsg.kt
  app/src/main/java/com/ovn/momo/feature/signup/SignUpScreen.kt
  app/src/main/java/com/ovn/momo/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/ovn/momo/feature/theme/Color.kt
  app/src/main/java/com/ovn/momo/feature/theme/Font.kt
  app/src/main/java/com/ovn/momo/feature/theme/Type.kt
  app/src/main/res/font/app_font.xml
  app/src/main/res/font/montserrat_alternates_bold.ttf
  app/src/main/res/font/montserrat_alternates_medium.ttf
  app/src/main/res/font/montserrat_alternates_regular.ttf
  app/src/main/res/font/pretendardbold.ttf
  app/src/main/res/font/pretendardmedium.ttf
  app/src/main/res/font/pretendardregular.ttf
  app/src/main/res/values/strings.xml
  app/src/test/java/android/util/Log.java
  app/src/test/java/com/ovn/momo/feature/signup/SignUpViewModelTest.kt
Labels: feature, design

#14 [feat] 어드민 진입 및 탭 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ovn/momo/app/AdminActivity.kt
  app/src/main/java/com/ovn/momo/core/navigation/AdminNavHost.kt
  app/src/main/java/com/ovn/momo/core/navigation/AdminNavItem.kt
  app/src/main/java/com/ovn/momo/core/utils/ClickUtils.kt
  app/src/main/java/com/ovn/momo/feature/admin/AdminBottomNavigation.kt
  app/src/main/java/com/ovn/momo/feature/admin/AdminScreen.kt
  app/src/main/java/com/ovn/momo/feature/mangeClub/ManageClub.kt
  app/src/main/java/com/ovn/momo/feature/member/Member.kt
  app/src/main/java/com/ovn/momo/feature/registerClub/AdminTopBar.kt
  app/src/main/java/com/ovn/momo/feature/registerClub/RegisterAdminInfo.kt
  app/src/main/java/com/ovn/momo/feature/session/Session.kt
  app/src/main/java/com/ovn/momo/feature/theme/Color.kt
  app/src/main/java/com/ovn/momo/feature/theme/Type.kt
  app/src/main/res/drawable/icon_back.xml
  app/src/main/res/drawable/icon_session.xml
  app/src/main/res/drawable/icon_setting.xml
  app/src/main/res/drawable/icon_user.xml
  app/src/main/res/values/strings.xml
Labels: feature

#15 [feat] 어드민 세션관리 탭 구현 - 1
  app/build.gradle
  app/src/main/java/com/ovn/momo/core/model/dto/SessionDto.kt
  app/src/main/java/com/ovn/momo/core/utils/DateTimeUtils.kt
  app/src/main/java/com/ovn/momo/feature/admin/AdminBottomNavigation.kt
  app/src/main/java/com/ovn/momo/feature/admin/AdminScreen.kt
  app/src/main/java/com/ovn/momo/feature/admin/AdminTopBar.kt
  app/src/main/java/com/ovn/momo/feature/registerClub/AdminTopBar.kt
  app/src/main/java/com/ovn/momo/feature/registerClub/RegisterAdminInfo.kt
  app/src/main/java/com/ovn/momo/feature/session/Session.kt
  app/src/main/java/com/ovn/momo/feature/session/SessionInfo.kt
  app/src/main/java/com/ovn/momo/feature/theme/Color.kt
  app/src/main/java/com/ovn/momo/feature/theme/Theme.kt
  app/src/main/java/com/ovn/momo/feature/theme/Type.kt
  app/src/main/res/drawable/icon_add.xml
  app/src/main/res/drawable/icon_excel.xml
  app/src/main/res/drawable/icon_go_to.xml
  app/src/main/res/drawable/icon_lock.xml
  app/src/main/res/drawable/icon_nexters.xml
  app/src/main/res/values/strings.xml
Labels: feature
